<?php

namespace Database\Seeders;

use App\Models\Profil;
use App\Models\User;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        User::create([
            'name'=> 'admin',
            'email'=> 'admin@gmail.com',
            'password' => bcrypt('admin')
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Katolik Santu Petrus',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105074',
            'akreditasi' => 'A',
            'alamat' => 'Jl. K.S. Tubun No. 3',
            'kecamatan' => 'Pontianak Selatan',
            'kelurahan' => 'Akcaya',
            'jumlah_siswa' => '873',
            'jumlah_guru' => '33',
            'jumlah_kelas' => '33',
            'jurusan' => 'belum tersedia',
            'latitude' => '0377731847149199',
            'longitude' => '109.3320116733079',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMAN 1',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105210',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Gusti Johan Idrus',
            'kecamatan' => 'Pontianak Selatan',
            'kelurahan' => 'Akcaya',
            'jumlah_siswa' => '1273',
            'jumlah_guru' => '62',
            'jumlah_kelas' => '36',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.04211683863421165',
            'longitude' => '109.32959388318875',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMAN 10',
            'jenis_sekolah' => 'SMA',
            'status' => 'Negeri',
            'npsn' => '30109801',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Purnama Komp. Purnama Agung V',
            'kecamatan' => 'Pontianak Selatan',
            'kelurahan' => 'Parit Tokaya',
            'jumlah_siswa' => '582',
            'jumlah_guru' => '41',
            'jumlah_kelas' => '19',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.05894265321516914',
            'longitude' => '109.33060156415937',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMAN 3',
            'jenis_sekolah' => 'SMA',
            'status' => 'Negeri',
            'npsn' => '30105212',
            'akreditasi' => 'A',
            'alamat' => 'Jl. WR Supratman',
            'kecamatan' => 'Pontianak Selatan',
            'kelurahan' => 'Benua Melayu Darat',
            'jumlah_siswa' => '1051',
            'jumlah_guru' => '61',
            'jumlah_kelas' => '28',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.03648985046435039',
            'longitude' => '109.3397624634936',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMAN 7',
            'jenis_sekolah' => 'SMA',
            'status' => 'Negeri',
            'npsn' => '30105205',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Sulawesi Dalam No. 10',
            'kecamatan' => 'Pontianak Selatan',
            'kelurahan' => 'Akcaya',
            'jumlah_siswa' => '887',
            'jumlah_guru' => '43',
            'jumlah_kelas' => '24',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.04530722825777618',
            'longitude' => '109.32741580983581',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Abdi Wacana',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105193',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Jend. A. Yani',
            'kecamatan' => 'Pontianak Selatan',
            'kelurahan' => 'Benua Melayu Darat',
            'jumlah_siswa' => '0',
            'jumlah_guru' => '11',
            'jumlah_kelas' => '9',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.04331928780106937',
            'longitude' => '109.33985119575654',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA  Kristen Immanuel',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105064',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Letjen Sutoyo Dalam',
            'kecamatan' => 'Pontianak Selatan',
            'kelurahan' => 'Parit Tokaya',
            'jumlah_siswa' => '933',
            'jumlah_guru' => '46',
            'jumlah_kelas' => '27',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.050753451616905254',
            'longitude' => '109.34098148369344',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Mujahidin',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105067',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Jend. A. Yani Komp Masjid Raya Mujahidin',
            'kecamatan' => 'Pontianak Selatan',
            'kelurahan' => 'Akcaya',
            'jumlah_siswa' => '567',
            'jumlah_guru' => '29',
            'jumlah_kelas' => '16',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.043034732000407624',
            'longitude' => '109.33742093549401',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Sultan Syarif Abdurrahman',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105192',
            'akreditasi' => 'C',
            'alamat' => 'Jl. Jend. A. Yani',
            'kecamatan' => 'Pontianak Selatan',
            'kelurahan' => 'Akcaya',
            'jumlah_siswa' => '0',
            'jumlah_guru' => '4',
            'jumlah_kelas' => '4',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.038042086219077655',
            'longitude' => '109.33446287396922',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Wisuda',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105207',
            'akreditasi' => 'C',
            'alamat' => 'Jl. Prof. M Yamin Gg. Gunung Kota',
            'kecamatan' => 'Pontianak Selatan',
            'kelurahan' => 'Kota Baru',
            'jumlah_siswa' => '47',
            'jumlah_guru' => '8',
            'jumlah_kelas' => '6',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.06430772618385432',
            'longitude' => '109.30624994770994',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA YPK',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105208',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Kapten Tendean',
            'kecamatan' => 'Pontianak Selatan',
            'kelurahan' => 'Benua Melayu Darat',
            'jumlah_siswa' => '4',
            'jumlah_guru' => '11',
            'jumlah_kelas' => '7',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.03616899445785991',
            'longitude' => '109.33774333901178',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMAN 6',
            'jenis_sekolah' => 'SMA',
            'status' => 'Negeri',
            'npsn' => '30105215',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Tani, Tanjung Raya 2',
            'kecamatan' => 'Pontianak Timur',
            'kelurahan' => 'Saigon',
            'jumlah_siswa' => '827',
            'jumlah_guru' => '46',
            'jumlah_kelas' => '24',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.039217218380096175',
            'longitude' => '109.36572438318872',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMAN 9',
            'jenis_sekolah' => 'SMA',
            'status' => 'Negeri',
            'npsn' => '30105203',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Tanjung Raya 2',
            'kecamatan' => 'Pontianak Timur',
            'kelurahan' => 'Saigon',
            'jumlah_siswa' => '698',
            'jumlah_guru' => '37',
            'jumlah_kelas' => '20',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.04918453648478271',
            'longitude' => '109.37245900205855',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Islam Haruniyah',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105082',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Tanjung Raya I No. 105',
            'kecamatan' => 'Pontianak Timur',
            'kelurahan' => 'Tambelan Sampit',
            'jumlah_siswa' => '174',
            'jumlah_guru' => '17',
            'jumlah_kelas' => '7',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.035877210145219565',
            'longitude' => '109.35293699969667',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA PGRI 1',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105069',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Tanjung Raya 2 Gg. Karya I',
            'kecamatan' => 'Pontianak Timur',
            'kelurahan' => 'Banjar Serasan',
            'jumlah_siswa' => '97',
            'jumlah_guru' => '5',
            'jumlah_kelas' => '5',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.03823604503823899',
            'longitude' => '109.35614171843532',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMAN 11',
            'jenis_sekolah' => 'SMA',
            'status' => 'Negeri',
            'npsn' => '69988824',
            'akreditasi' => 'C',
            'alamat' => 'Jl. Nipah Kuning Dalam',
            'kecamatan' => 'Pontianak Barat',
            'kelurahan' => 'Pal Lima',
            'jumlah_siswa' => '737',
            'jumlah_guru' => '44',
            'jumlah_kelas' => '20',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.01431012354479785',
            'longitude' => '109.29408452639298',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMAN 2',
            'jenis_sekolah' => 'SMA',
            'status' => 'Negeri',
            'npsn' => '30105211',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Re. Martadinata',
            'kecamatan' => 'Pontianak Barat',
            'kelurahan' => 'Sungai Jawi Dalam',
            'jumlah_siswa' => '1086',
            'jumlah_guru' => '49',
            'jumlah_kelas' => '32',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.015114623271474144',
            'longitude' => '109.31629000832886',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Al-Islah Baitul Mal',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105078',
            'akreditasi' => 'B',
            'alamat' => 'Jl. H. Rais A. Rachman Gg. Lawu',
            'kecamatan' => 'Pontianak Barat',
            'kelurahan' => 'Pal Lima',
            'jumlah_siswa' => '91',
            'jumlah_guru' => '11',
            'jumlah_kelas' => '5',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.020371438031094976',
            'longitude' => '109.31231347386789',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Kapuas',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105085',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Tabrani Ahmad',
            'kecamatan' => 'Pontianak Barat',
            'kelurahan' => 'Sungai Jawi Dalam',
            'jumlah_siswa' => '30',
            'jumlah_guru' => '9',
            'jumlah_kelas' => '3',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.016384415571071977',
            'longitude' => '109.31169940560197',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Koperasi',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105063',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Komyos Sudarso, Gg. Tebu Tiga',
            'kecamatan' => 'Pontianak Barat',
            'kelurahan' => 'Sungai Beliung',
            'jumlah_siswa' => '147',
            'jumlah_guru' => '16',
            'jumlah_kelas' => '8',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.0067112960418409095',
            'longitude' => '109.30968715857286',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Nahdlatus Syubban',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30107392',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Apel Gg. Apel VII',
            'kecamatan' => 'Pontianak Barat',
            'kelurahan' => 'Sungai Jawi Luar',
            'jumlah_siswa' => '118',
            'jumlah_guru' => '8',
            'jumlah_kelas' => '6',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.014341661092324582',
            'longitude' => '109.31944912442187',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Tunas Bhakti',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105206',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Tebu',
            'kecamatan' => 'Pontianak Barat',
            'kelurahan' => 'Sungai Beliung',
            'jumlah_siswa' => '120',
            'jumlah_guru' => '7',
            'jumlah_kelas' => '5',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.009491107673515476',
            'longitude' => '109.30968222466718',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Islam Al-Asy Ariyyah',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30109706',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Khatulistiwa Gg. Parwasa',
            'kecamatan' => 'Pontianak Utara',
            'kelurahan' => 'Siantan Tengah',
            'jumlah_siswa' => '123',
            'jumlah_guru' => '5',
            'jumlah_kelas' => '4',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.015503359888950914',
            'longitude' => '109.34361539927647',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Islam Al-Aziz',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '69977460',
            'akreditasi' => 'C',
            'alamat' => 'Jl. Parit Pangeran GG. Permata Sari',
            'kecamatan' => 'Pontianak Utara',
            'kelurahan' => 'Siantan Hulu',
            'jumlah_siswa' => '84',
            'jumlah_guru' => '9',
            'jumlah_kelas' => '3',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.007754856657046866',
            'longitude' => '109.35443326401321',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Islam Al-Husna',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '69989184',
            'akreditasi' => 'B',
            'alamat' => 'Jl. 28 Oktober Gg. Hidayah',
            'kecamatan' => 'Pontianak Utara',
            'kelurahan' => 'Siantan Hulu',
            'jumlah_siswa' => '123',
            'jumlah_guru' => '9',
            'jumlah_kelas' => '4',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.0026335379871644865',
            'longitude' => '109.36819743226071',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Islam Darul Amin',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '69978634',
            'akreditasi' => 'C',
            'alamat' => 'Jl. Dharma Putra No.18 B',
            'kecamatan' => 'Pontianak Utara',
            'kelurahan' => 'Siantan Hilir',
            'jumlah_siswa' => '127',
            'jumlah_guru' => '10',
            'jumlah_kelas' => '5',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.0024918388496846114',
            'longitude' => '109.34128439319456',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMAN 5',
            'jenis_sekolah' => 'SMA',
            'status' => 'Negeri',
            'npsn' => '30105214',
            'akreditasi' => 'A',
            'alamat' => 'Jl. SMU 5 Gg. Damai',
            'kecamatan' => 'Pontianak Utara',
            'kelurahan' => 'Batulayang',
            'jumlah_siswa' => '1058',
            'jumlah_guru' => '46',
            'jumlah_kelas' => '27',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.0022132787534148816',
            'longitude' => '109.32468752677808',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Abdi Agape',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105077',
            'akreditasi' => 'C',
            'alamat' => 'Jl. Selat Sumba III Siantan',
            'kecamatan' => 'Pontianak Utara',
            'kelurahan' => 'Siantan Tengah',
            'jumlah_siswa' => '16',
            'jumlah_guru' => '0',
            'jumlah_kelas' => '2',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.012940612929612204',
            'longitude' => '109.34692133669903',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Islam Hisada',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30109871',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Kebangkitan Nasional / Jl. Purnajaya',
            'kecamatan' => 'Pontianak Utara',
            'kelurahan' => 'Batulayang',
            'jumlah_siswa' => '145',
            'jumlah_guru' => '14',
            'jumlah_kelas' => '6',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.012653384875162469',
            'longitude' => '109.32501650299442',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Maranatha',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105209',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Gst. Situt Machmud No. 113',
            'kecamatan' => 'Pontianak Utara',
            'kelurahan' => 'Siantan Tengah',
            'jumlah_siswa' => '300',
            'jumlah_guru' => '20',
            'jumlah_kelas' => '10',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.01845663410853584',
            'longitude' => '109.34433728105088',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Santo Fransiskus Asisi',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105072',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Selat Sumba 3',
            'kecamatan' => 'Pontianak Utara',
            'kelurahan' => 'Siantan Tengah',
            'jumlah_siswa' => '296',
            'jumlah_guru' => '11',
            'jumlah_kelas' => '15',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.016525114911785342',
            'longitude' => '109.34619343241604',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Islam Al-Baisuny',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '69951983',
            'akreditasi' => 'C',
            'alamat' => 'Jl. Petani No.4',
            'kecamatan' => 'Pontianak Kota',
            'kelurahan' => 'Sungai Bangkong',
            'jumlah_siswa' => '73',
            'jumlah_guru' => '3',
            'jumlah_kelas' => '3',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.05059677081385164',
            'longitude' => '109.30450320895353',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Islam Ar Rahim',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '69986638',
            'akreditasi' => 'C',
            'alamat' => 'Jl. H.Rais A.Rachman Gg. Bukit Gading No.80 A',
            'kecamatan' => 'Pontianak Kota',
            'kelurahan' => 'Sungai Jawi',
            'jumlah_siswa' => '44',
            'jumlah_guru' => '5',
            'jumlah_kelas' => '3',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.02081025580358642',
            'longitude' => '109.3219728788786',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Tahfizhul Quran Labbaik',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '69979937',
            'akreditasi' => 'C',
            'alamat' => 'Jl. Ampera Gg. Masjid No.02',
            'kecamatan' => 'Pontianak Kota',
            'kelurahan' => 'Sungai Jawi',
            'jumlah_siswa' => '218',
            'jumlah_guru' => '9',
            'jumlah_kelas' => '7',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.051363330982099456',
            'longitude' => '109.30173907635292',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Al-Mumtaz',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '69981698',
            'akreditasi' => 'C',
            'alamat' => 'Jl. Dr. Wahidin Gg. Sepakat 2',
            'kecamatan' => 'Pontianak Kota',
            'kelurahan' => 'Sungai Jawi',
            'jumlah_siswa' => '148',
            'jumlah_guru' => '15',
            'jumlah_kelas' => '8',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.03810188617767937',
            'longitude' => '109.31111110790584',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMAN 4',
            'jenis_sekolah' => 'SMA',
            'status' => 'Negeri',
            'npsn' => '30105213',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Dr. Wahidin Sudirohusodo',
            'kecamatan' => 'Pontianak Kota',
            'kelurahan' => 'Sungai Jawi',
            'jumlah_siswa' => '950',
            'jumlah_guru' => '54',
            'jumlah_kelas' => '27',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.03306454939179144',
            'longitude' => '109.30631164227616',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMAN 8',
            'jenis_sekolah' => 'SMA',
            'status' => 'Negeri',
            'npsn' => '30105204',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Ampera',
            'kecamatan' => 'Pontianak Kota',
            'kelurahan' => 'Sungai Jawi',
            'jumlah_siswa' => '814',
            'jumlah_guru' => '45',
            'jumlah_kelas' => '23',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.05134306748158891',
            'longitude' => '109.29804305435333',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Bina Utama',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105080',
            'akreditasi' => 'A',
            'alamat' => 'Jl. H. Rais A. Rahman',
            'kecamatan' => 'Pontianak Kota',
            'kelurahan' => 'Sungai Jawi',
            'jumlah_siswa' => '271',
            'jumlah_guru' => '26',
            'jumlah_kelas' => '10',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.022998919755164868',
            'longitude' => '109.31349689977705',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Islam Bawari',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105079',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Merdeka Barat',
            'kecamatan' => 'Pontianak Kota',
            'kelurahan' => 'Mariana',
            'jumlah_siswa' => '420',
            'jumlah_guru' => '21',
            'jumlah_kelas' => '13',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.021905953109149476',
            'longitude' => '109.32990430877197',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Muhammadiyah 2',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105065',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Dr. Sutomo Gg. Karya I',
            'kecamatan' => 'Pontianak Kota',
            'kelurahan' => 'Sungai Bangkong',
            'jumlah_siswa' => '90',
            'jumlah_guru' => '9',
            'jumlah_kelas' => '6',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.047997772572866866',
            'longitude' => '109.3157889296098',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Panca Bhakti',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105068',
            'akreditasi' => 'A',
            'alamat' => 'Jl. H. Rais A. Rahman',
            'kecamatan' => 'Pontianak Kota',
            'kelurahan' => 'Sungai Jawi',
            'jumlah_siswa' => '23',
            'jumlah_guru' => '11',
            'jumlah_kelas' => '4',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.022288238615199164',
            'longitude' => '109.31701945435316',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Rahadi Oesman',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105071',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Alianyang No. 123',
            'kecamatan' => 'Pontianak Kota',
            'kelurahan' => 'Sungai Bangkong',
            'jumlah_siswa' => '32',
            'jumlah_guru' => '6',
            'jumlah_kelas' => '5',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.03319500978907104',
            'longitude' => '109.31998572551794',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Santo Paulus',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105086',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Arif Rahman Hakim No.92',
            'kecamatan' => 'Pontianak Kota',
            'kelurahan' => 'Darat Sekip',
            'jumlah_siswa' => '829',
            'jumlah_guru' => '32',
            'jumlah_kelas' => '25',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.027978752574457477',
            'longitude' => '109.33565982924718',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA WALISONGO',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30107395',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Ampera No.1 A',
            'kecamatan' => 'Pontianak Kota',
            'kelurahan' => 'Sungai Jawi',
            'jumlah_siswa' => '120',
            'jumlah_guru' => '5',
            'jumlah_kelas' => '5',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.047409425948540224',
            'longitude' => '109.29587691820507',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Islam Al-Azhar 10',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '69830077',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Jenderal Ahmad Yani',
            'kecamatan' => 'Pontianak Tenggara',
            'kelurahan' => 'Bansir Laut',
            'jumlah_siswa' => '123',
            'jumlah_guru' => '12',
            'jumlah_kelas' => '8',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.05843080983501814',
            'longitude' => '109.3511153525059',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Pelita Cemerlang',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '69978202',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Perdana No.8',
            'kecamatan' => 'Pontianak Tenggara',
            'kelurahan' => 'Bansir Laut',
            'jumlah_siswa' => '175',
            'jumlah_guru' => '15',
            'jumlah_kelas' => '8',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.05477308465248798',
            'longitude' => '109.34451566486564',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Bina Mulia',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30107389',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Abdul Rachman Saleh No. A1',
            'kecamatan' => 'Pontianak Tenggara',
            'kelurahan' => 'Bangka Belitung Laut',
            'jumlah_siswa' => '207',
            'jumlah_guru' => '16',
            'jumlah_kelas' => '12',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.057220086311904415',
            'longitude' => '109.3550742984848',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Budi Oetomo',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30107838',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Parit H. Husin 2',
            'kecamatan' => 'Pontianak Tenggara',
            'kelurahan' => 'Bangka Belitung Darat',
            'jumlah_siswa' => '40',
            'jumlah_guru' => '6',
            'jumlah_kelas' => '3',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.07190845324972404',
            'longitude' => '109.35502043161367',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Gembala BaiK',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105075',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Jenderal Ahmad Yani',
            'kecamatan' => 'Pontianak Tenggara',
            'kelurahan' => 'Bangka Belitung Darat',
            'jumlah_siswa' => '688',
            'jumlah_guru' => '36',
            'jumlah_kelas' => '21',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.06867876550571957',
            'longitude' => '109.35929878763396',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Islamiyah',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105084',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Imam Bonjol No.88',
            'kecamatan' => 'Pontianak Tenggara',
            'kelurahan' => 'Bansir Laut',
            'jumlah_siswa' => '102',
            'jumlah_guru' => '11',
            'jumlah_kelas' => '3',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.048711085668572913',
            'longitude' => '109.35658147733423',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Muhammadiyah 1',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105066',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Parit H. Husin 2',
            'kecamatan' => 'Pontianak Tenggara',
            'kelurahan' => 'Bansir Darat',
            'jumlah_siswa' => '684',
            'jumlah_guru' => '37',
            'jumlah_kelas' => '20',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.06922894013015511',
            'longitude' => '109.35230874669084',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Santun Untan',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '30105140',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Daya Nasional',
            'kecamatan' => 'Pontianak Tenggara',
            'kelurahan' => 'Bansir Laut',
            'jumlah_siswa' => '111',
            'jumlah_guru' => '9',
            'jumlah_kelas' => '6',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.05068706748041997',
            'longitude' => '109.35212261202408',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMK Al-Madani',
            'jenis_sekolah' => 'SMK',
            'status' => 'Swasta',
            'npsn' => '30105195',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Sungai Raya Dalam Komp. Mitra Utama 3',
            'kecamatan' => 'Pontianak Tenggara',
            'kelurahan' => 'Bangka Belitung Darat',
            'jumlah_siswa' => '146',
            'jumlah_guru' => '20',
            'jumlah_kelas' => '9',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.07173783616526234',
            'longitude' => '109.35881090895259',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMK Boedi Utomo',
            'jenis_sekolah' => 'SMK',
            'status' => 'Swasta',
            'npsn' => '30105198',
            'akreditasi' => 'C',
            'alamat' => 'Jl. Parit H. Husin II Komp. Balimas 3',
            'kecamatan' => 'Pontianak Tenggara',
            'kelurahan' => 'Bangka Belitung Darat',
            'jumlah_siswa' => '0',
            'jumlah_guru' => '5',
            'jumlah_kelas' => '3',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.02006257648254814',
            'longitude' => '109.3309184605112',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMK Kesehatan Reformasi',
            'jenis_sekolah' => 'SMK',
            'status' => 'Swasta',
            'npsn' => '69947508',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Purnama Agung 7 Blok C.11-13',
            'kecamatan' => 'Pontianak Selatan',
            'kelurahan' => 'Parit Tokaya',
            'jumlah_siswa' => '151',
            'jumlah_guru' => '13',
            'jumlah_kelas' => '16',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.05957453735632035',
            'longitude' => '109.32789824327135',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMKN 3',
            'jenis_sekolah' => 'SMK',
            'status' => 'Negeri',
            'npsn' => '30105231',
            'akreditasi' => 'A',
            'alamat' => 'Jl. S. Parman',
            'kecamatan' => 'Pontianak Selatan',
            'kelurahan' => 'Benua Melayu Darat',
            'jumlah_siswa' => '1111',
            'jumlah_guru' => '49',
            'jumlah_kelas' => '31',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.03491137563856041',
            'longitude' => '109.33826889760526',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMKN 5',
            'jenis_sekolah' => 'SMK',
            'status' => 'Negeri',
            'npsn' => '30105219',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Jenderal Ahmad Yani No.4',
            'kecamatan' => 'Pontianak Selatan',
            'kelurahan' => 'Akcaya',
            'jumlah_siswa' => '887',
            'jumlah_guru' => '57',
            'jumlah_kelas' => '20',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.03703400709502854',
            'longitude' => '109.33376066319506',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMK SMTI Pontianak',
            'jenis_sekolah' => 'SMK',
            'status' => 'Negeri',
            'npsn' => '30108179',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Sulawesi Dalam No.31',
            'kecamatan' => 'Pontianak Selatan',
            'kelurahan' => 'Akcaya',
            'jumlah_siswa' => '0',
            'jumlah_guru' => '50',
            'jumlah_kelas' => '24',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.044733938166252596',
            'longitude' => '109.32724211422865',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMK Kristen Immanuel',
            'jenis_sekolah' => 'SMK',
            'status' => 'Swasta',
            'npsn' => '30105216',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Letnan Jendral Sutoyo No.1',
            'kecamatan' => 'Pontianak Selatan',
            'kelurahan' => 'Parit Tokaya',
            'jumlah_siswa' => '0',
            'jumlah_guru' => '26',
            'jumlah_kelas' => '21',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.050836424237174015',
            'longitude' => '109.34194699464696',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMK LKIA',
            'jenis_sekolah' => 'SMK',
            'status' => 'Swasta',
            'npsn' => '30105217',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Jenderal Ahmad Yani No.5',
            'kecamatan' => 'Pontianak Selatan',
            'kelurahan' => 'Akcaya',
            'jumlah_siswa' => '0',
            'jumlah_guru' => '14',
            'jumlah_kelas' => '13',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.03767037136925712',
            'longitude' => '109.33385470737086',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMK Santa Maria',
            'jenis_sekolah' => 'SMK',
            'status' => 'Swasta',
            'npsn' => '30105240',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Karel Satsuit Tubun No.03',
            'kecamatan' => 'Pontianak Selatan',
            'kelurahan' => 'Akcaya',
            'jumlah_siswa' => '0',
            'jumlah_guru' => '13',
            'jumlah_kelas' => '10',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.03771779103186512',
            'longitude' => '109.33189728840217',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMK YPK',
            'jenis_sekolah' => 'SMK',
            'status' => 'Swasta',
            'npsn' => '30105242',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Jend. A. Yani / Kapt.Tendean Gg.Sehat Ptk',
            'kecamatan' => 'Pontianak Selatan',
            'kelurahan' => 'Benua Melayu Darat',
            'jumlah_siswa' => '0',
            'jumlah_guru' => '14',
            'jumlah_kelas' => '7',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.022889139150244243',
            'longitude' => '109.33009040776648',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMKN 7',
            'jenis_sekolah' => 'SMK',
            'status' => 'Negeri',
            'npsn' => '30107398',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Tj. Raya II',
            'kecamatan' => 'Pontianak Timur',
            'kelurahan' => 'Saigon',
            'jumlah_siswa' => '0',
            'jumlah_guru' => '48',
            'jumlah_kelas' => '23',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.04841102767266921',
            'longitude' => '109.37364133243288',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMK Mandiri',
            'jenis_sekolah' => 'SMK',
            'status' => 'Swasta',
            'npsn' => '30105218',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Tj. Raya II No.8',
            'kecamatan' => 'Pontianak Timur',
            'kelurahan' => 'Saigon',
            'jumlah_siswa' => '232',
            'jumlah_guru' => '18',
            'jumlah_kelas' => '18',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.04462008280097892',
            'longitude' => '109.36905086784719',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMK Bina Dharma',
            'jenis_sekolah' => 'SMK',
            'status' => 'Swasta',
            'npsn' => '69946866',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Kom Yos Sudarso Gg. Rambutan 2 No.27',
            'kecamatan' => 'Pontianak Barat',
            'kelurahan' => 'Sungai Beliung',
            'jumlah_siswa' => '0',
            'jumlah_guru' => '22',
            'jumlah_kelas' => '9',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.004487701413315798',
            'longitude' => '109.30840999397347',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMKN 4',
            'jenis_sekolah' => 'SMK',
            'status' => 'Negeri',
            'npsn' => '30105230',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Komodor Yos Sudarso No.1',
            'kecamatan' => 'Pontianak Barat',
            'kelurahan' => 'Sungai Beliung',
            'jumlah_siswa' => '1999',
            'jumlah_guru' => '113',
            'jumlah_kelas' => '35',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.004641417035123701',
            'longitude' => '109.30582639348903',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMKN 9',
            'jenis_sekolah' => 'SMK',
            'status' => 'Negeri',
            'npsn' => '30110024',
            'akreditasi' => 'C',
            'alamat' => 'Jl. Tabrani Ahmad',
            'kecamatan' => 'Pontianak Barat',
            'kelurahan' => 'Pal Lima',
            'jumlah_siswa' => '369',
            'jumlah_guru' => '27',
            'jumlah_kelas' => '16',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.025277686097525592',
            'longitude' => '109.29258655014897',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMK Ethika',
            'jenis_sekolah' => 'SMK',
            'status' => 'Swasta',
            'npsn' => '30105200',
            'akreditasi' => 'C',
            'alamat' => 'Jl. Kom Yos Sudarso No.8',
            'kecamatan' => 'Pontianak Barat',
            'kelurahan' => 'Sungai Jawi Luar',
            'jumlah_siswa' => '0',
            'jumlah_guru' => '2',
            'jumlah_kelas' => '3',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.006184111629644607',
            'longitude' => '109.3174909966825',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMK Koperasi',
            'jenis_sekolah' => 'SMK',
            'status' => 'Swasta',
            'npsn' => '30105202',
            'akreditasi' => 'C',
            'alamat' => 'Jl. Kom Yos Sudarso Gg. Tebu 3',
            'kecamatan' => 'Pontianak Barat',
            'kelurahan' => 'Sungai Beliung',
            'jumlah_siswa' => '0',
            'jumlah_guru' => '15',
            'jumlah_kelas' => '11',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.007097253847584306',
            'longitude' => '109.30535155017476',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMK Muhammadiyah',
            'jenis_sekolah' => 'SMK',
            'status' => 'Swasta',
            'npsn' => '30105233',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Komodor Yos Sudarso',
            'kecamatan' => 'Pontianak Barat',
            'kelurahan' => 'Sungai Beliung',
            'jumlah_siswa' => '156',
            'jumlah_guru' => '12',
            'jumlah_kelas' => '9',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.0044896405416036565',
            'longitude' => '109.30157461077866',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMK Pelayaran Pembangunan',
            'jenis_sekolah' => 'SMK',
            'status' => 'Swasta',
            'npsn' => '30108178',
            'akreditasi' => 'Tidak Terakreditasi',
            'alamat' => 'Jl. Kom Yos Sudarso Komp. Yuka Jalur Kosong',
            'kecamatan' => 'Pontianak Barat',
            'kelurahan' => 'Sungai Beliung',
            'jumlah_siswa' => '0',
            'jumlah_guru' => '2',
            'jumlah_kelas' => '6',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.0033764793365265414',
            'longitude' => '109.29901762713955',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMKN 2',
            'jenis_sekolah' => 'SMK',
            'status' => 'Negeri',
            'npsn' => '30105232',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Khatulistiwa No.215',
            'kecamatan' => 'Pontianak Utara',
            'kelurahan' => 'Siantan Hilir',
            'jumlah_siswa' => '1041',
            'jumlah_guru' => '63',
            'jumlah_kelas' => '21',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.005496232659103269',
            'longitude' => '109.3303487038671',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMKN 6',
            'jenis_sekolah' => 'SMK',
            'status' => 'Negeri',
            'npsn' => '30105220',
            'akreditasi' => 'A',
            'alamat' => 'Jl. 28 Oktober No.2',
            'kecamatan' => 'Pontianak Utara',
            'kelurahan' => 'Siantan Hilir',
            'jumlah_siswa' => '0',
            'jumlah_guru' => '41',
            'jumlah_kelas' => '18',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.008722689575154093',
            'longitude' => '109.36517206302257',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMKN 8',
            'jenis_sekolah' => 'SMK',
            'status' => 'Negeri',
            'npsn' => '30109745',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Budi Utomo',
            'kecamatan' => 'Pontianak Utara',
            'kelurahan' => 'Siantan Tengah',
            'jumlah_siswa' => '0',
            'jumlah_guru' => '47',
            'jumlah_kelas' => '21',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.005983199026701278',
            'longitude' => '109.35092962371074',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMK Abdi Agape',
            'jenis_sekolah' => 'SMK',
            'status' => 'Swasta',
            'npsn' => '30105194',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Gusti Situt Mahmud Gg. Selat Sumba 3',
            'kecamatan' => 'Pontianak Utara',
            'kelurahan' => 'Siantan Tengah',
            'jumlah_siswa' => '220',
            'jumlah_guru' => '7',
            'jumlah_kelas' => '14',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.012963920897825842',
            'longitude' => '109.34705102982934',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMK Bhineka Tunggal Ika',
            'jenis_sekolah' => 'SMK',
            'status' => 'Swasta',
            'npsn' => '30105196',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Khatulistiwa Gg. Dharma Putra No.6',
            'kecamatan' => 'Pontianak Utara',
            'kelurahan' => 'Siantan Hilir',
            'jumlah_siswa' => '0',
            'jumlah_guru' => '10',
            'jumlah_kelas' => '7',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.008907862904360393',
            'longitude' => '109.34099587991076',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMK Cinta Bumi Khatulistiwa',
            'jenis_sekolah' => 'SMK',
            'status' => 'Swasta',
            'npsn' => '30105199',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Selat Panjang Gg. Wartawan No. 34',
            'kecamatan' => 'Pontianak Utara',
            'kelurahan' => 'Siantan Hulu',
            'jumlah_siswa' => '0',
            'jumlah_guru' => '5',
            'jumlah_kelas' => '5',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.01083427397433078',
            'longitude' => '109.36379441416784',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMK Putra Khatulistiwa',
            'jenis_sekolah' => 'SMK',
            'status' => 'Swasta',
            'npsn' => '30105238',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Dharma Putra No. 66',
            'kecamatan' => 'Pontianak Utara',
            'kelurahan' => 'Siantan Hilir',
            'jumlah_siswa' => '0',
            'jumlah_guru' => '14',
            'jumlah_kelas' => '13',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.006659364405126458',
            'longitude' => '109.34099072551778',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMKN 1',
            'jenis_sekolah' => 'SMK',
            'status' => 'Negeri',
            'npsn' => '30105243',
            'akreditasi' => 'A',
            'alamat' => 'Jl. Danau Sentarum',
            'kecamatan' => 'Pontianak Kota',
            'kelurahan' => 'Sungai Bangkong',
            'jumlah_siswa' => '1055',
            'jumlah_guru' => '69',
            'jumlah_kelas' => '31',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.04208923946842817',
            'longitude' => '109.31205668175589',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMK Bina Utama',
            'jenis_sekolah' => 'SMK',
            'status' => 'Swasta',
            'npsn' => '30105197',
            'akreditasi' => 'C',
            'alamat' => 'Jl. H. Rais A. Rahman',
            'kecamatan' => 'Pontianak Kota',
            'kelurahan' => 'Sungai Jawi',
            'jumlah_siswa' => '0',
            'jumlah_guru' => '19',
            'jumlah_kelas' => '13',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.02258820283510703',
            'longitude' => '109.31320014446557',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMK Muhammadiyah 2',
            'jenis_sekolah' => 'SMK',
            'status' => 'Swasta',
            'npsn' => '69757904',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Dr. Sutomo, Gg. Karya',
            'kecamatan' => 'Pontianak Kota',
            'kelurahan' => 'Sungai Bangkong',
            'jumlah_siswa' => '42',
            'jumlah_guru' => '6',
            'jumlah_kelas' => '6',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.0478570846351672',
            'longitude' => '109.31579731506115',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMK PGRI',
            'jenis_sekolah' => 'SMK',
            'status' => 'Swasta',
            'npsn' => '30105235',
            'akreditasi' => 'B',
            'alamat' => 'Jl. Alianyang',
            'kecamatan' => 'Pontianak Kota',
            'kelurahan' => 'Sungai Bangkong',
            'jumlah_siswa' => '0',
            'jumlah_guru' => '13',
            'jumlah_kelas' => '12',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.0321449139059153',
            'longitude' => '109.32429153989497',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMAN 12',
            'jenis_sekolah' => 'SMA',
            'status' => 'Negeri',
            'npsn' => '70011405',
            'akreditasi' => 'Tidak Terakreditasi',
            'alamat' => 'Jl. Budi Utomo',
            'kecamatan' => 'Pontianak Utara',
            'kelurahan' => 'Siantan Tengah',
            'jumlah_siswa' => '360',
            'jumlah_guru' => '17',
            'jumlah_kelas' => '11',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.006299345595073075',
            'longitude' => '109.35090204743217',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Kristen Kalam Kudus',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '70030285',
            'akreditasi' => 'Tidak Terakreditasi',
            'alamat' => 'Jl. Purnama No. 52',
            'kecamatan' => 'Pontianak Selatan',
            'kelurahan' => 'Parit Tokaya',
            'jumlah_siswa' => '7',
            'jumlah_guru' => '0',
            'jumlah_kelas' => '1',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.05108147316653647',
            'longitude' => '109.33230231504575',
        ]);

        Profil::create([
            'nama_sekolah' => 'SMA Islam Raudlatul Muhibbin',
            'jenis_sekolah' => 'SMA',
            'status' => 'Swasta',
            'npsn' => '70014482',
            'akreditasi' => 'Tidak Terakreditasi',
            'alamat' => 'Jl. Selat Panjang 2',
            'kecamatan' => 'Pontianak Utara',
            'kelurahan' => 'Siantan Hulu',
            'jumlah_siswa' => '82',
            'jumlah_guru' => '1',
            'jumlah_kelas' => '3',
            'jurusan' => 'belum tersedia',
            'latitude' => '-0.006271976413964554',
            'longitude' => '109.3749530647248',
        ]);
    }
}
